### ISSUE TITLE
Translation mistake: "Transfer Files" should be translated as 「傳輸檔案」

### ISSUE THREAD

**Issue by nicolas-chan-42** [AnLinkSoft/AnLinkTranslation#10]
https://github.com/AnLinkSoft/AnLinkTranslation/blob/7c7ce3390344b409917115ad42744b8faa7bd326/%E7%B9%81%E9%AB%94%E4%B8%AD%E6%96%87(%E9%A6%99%E6%B8%AF).lang#L10

"Transfer Files" should be translated as _「傳輸檔案」_ instead of _「傳輸檔」_.
So, the whole sentence should be translated as _請在連接手機後再次嘗試「傳輸檔案」_.

**Comment by AnLinkSoft** [comment]
Please fork this repository and make pull request.

**Comment by AnLinkSoft** [comment]
#14
