### ISSUE TITLE
Translation mistake: "Disable" should be translated as "停用"

### ISSUE THREAD

**Issue by nicolas-chan-42** [AnLinkSoft/AnLinkTranslation#11]
https://github.com/AnLinkSoft/AnLinkTranslation/blob/7c7ce3390344b409917115ad42744b8faa7bd326/%E7%B9%81%E9%AB%94%E4%B8%AD%E6%96%87(%E9%A6%99%E6%B8%AF).lang#L19

"Disable" should be translated as "停用" instead of "禁用", which means prohibiting or banning the use of something.
- "停用" means stopping the use/function of something, e.g. 停用火警系統=Disable the fire alarm system;
- "禁用" means prohibiting or banning the use/function of something, e.g. 禁用藥物=drugs prohibited

Obviously, they are not the same and "Disable WiFi connection" should be translated as "停用 WiFi 連接"

**Comment by AnLinkSoft** [comment]
#14
