### ISSUE TITLE
Translation improvement: "settings" should be translated as "設定"

### ISSUE THREAD

**Issue by nicolas-chan-42** [AnLinkSoft/AnLinkTranslation#12]
https://github.com/AnLinkSoft/AnLinkTranslation/blob/7c7ce3390344b409917115ad42744b8faa7bd326/%E7%B9%81%E9%AB%94%E4%B8%AD%E6%96%87(%E9%A6%99%E6%B8%AF).lang#L26

In Chinese,
- "設置" (noun) roughly means the (physical) placement or setup of something;
- "設定" (noun) means the settings/configurations of something

**Comment by nicolas-chan-42** [comment]
https://github.com/AnLinkSoft/AnLinkTranslation/blob/7c7ce3390344b409917115ad42744b8faa7bd326/%E7%B9%81%E9%AB%94%E4%B8%AD%E6%96%87(%E9%A6%99%E6%B8%AF).lang#L32

Similar for this line

**Comment by AnLinkSoft** [comment]
#14
