### ISSUE TITLE
Some unclear strings

### ISSUE THREAD

**Issue by bzzrak** [AnLinkSoft/AnLinkTranslation#51]
Hi, I'm in process of updating the Serbian translation for the latest Anlink and I noticed 3 new strings that I don't understand:

`Create folder translation file` -- what does this do? It appears in the settings.
`There is no device that hasn't install the driver` -- what does this mean? And when does this message appear?
`Configured Phone` -- when does this message appear?
Thanks.

**Comment by bzzrak** [comment]
One more thing: what does `Shrink at screen edge` do?

**Comment by AnLinkSoft** [comment]
`Create folder translation file` means when we created the folder for the storage data, people may not understand what it means. So, we create a file to give user a hint about it.
`There is no device that hasn't install the driver` is located at the driver installation, we scan the computer and enumerate the devices which is not installed the generic drivers.
`Configured Phone` in WiFi Manager. When you paired a new phone, the item name would be showed as it.
`Shrink at screen edge` means the main window will shrink when user drag over the screen edge

**Comment by bzzrak** [comment]
Thanks!
The naming of that last option is really confusing. I translated it as roughly "Hide remote window when it's right by the edge of the screen".
